# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  push:
    branches: [main, dev]

  pull_request_target:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.8

      - uses: Gr1N/setup-poetry@v7

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - uses: suo/flake8-github-action@v1

      - uses: jakebailey/pyright-action@v1

  analyze:
    runs-on: ubuntu-latest
    name: CodeQL Analyze

    if: "!github.base_ref"

    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
